### ISSUE TITLE
QString overloaded functions Windows problem

### ISSUE THREAD

**Issue by matkuki** [jerous86/nimqt#30]
Hi,

Specs:
- Windows 10 x64
- Nim 1.6.14
- latest nimqt

After upgrading `nimqt` today, I get a lot of errors for the lines that I manually commented out in the below screenshot:
![image](https://github.com/jerous86/nimqt/assets/10289651/6e9bee77-6be0-45e5-bfff-83f0811bd7c6)
The errors that are thrown are:
```
C:\Users\matic\.nimble\pkgs\nimqt-0.1\nimqt\qtcore\qstring.nim(189, 1) Error: redefinition of 'arg'; previous declaration here: C:\Users\matic\.nimble\pkgs\nimqt-0.1\nimqt\qtcore\qstring.nim(179, 6)
stack trace: (most recent call last)
```

**Comment by jerous86** [comment]
This one's already been reported. Will try to resolve it soon, but been busy lately.
And the release of nim2 will not help :)

**Comment by jerous86** [comment]
I think it should work now, can you confirm?

**Comment by matkuki** [comment]
Just reinstalled and still get this:
```
C:\Users\matic\.nimble\pkgs\nimqt-0.1\nimqt\qtcore\qstring.nim(189, 1) Error: redefinition of 'arg'; previous declaration here: C:\Users\matic\.nimble\pkgs\nimqt-0.1\nimqt\qtcore\qstring.nim(179, 6)
stack trace: (most recent call last)
```

**Comment by jerous86** [comment]
That looks like the exact same line numbers as in the original issue, while they have changed, so it must be something with you having two versions, and using the wrong one.

I'll maybe should also update the version number of nimqt ... :)

**Comment by matkuki** [comment]
Hey @jerous86 ,

Just removed `nimqt` with `nimble` and checked it was deleted from the `nimble` directory, then reinstalled with:
```bash
$ nimble install https://github.com/jerous86/nimqt
```
... but the problem persists.
And this is in my `.nimble ` directory:
![image](https://github.com/jerous86/nimqt/assets/10289651/588c39c0-6ce2-4818-8ae8-d3a0ae61e142)

**Comment by jerous86** [comment]
There is something fishy going on since I've added some tags, and I think that's what causing some problems. Any idea for that?

`nimble install https://github.com/jerous86/nimqt@#head`

should install the latest version.
